version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - generoushands_network

  db:
    image: postgres:14
    container_name: generoushands_db
    environment:
      POSTGRES_USER: generous_user
      POSTGRES_PASSWORD: generous_pass
      POSTGRES_DB: generoushands
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - generoushands_network

networks:
  generoushands_network:
    name: generoushands_network
    driver: bridge

volumes:
  db_data:
