name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/projects/generoushands/api
            git pull origin main

            # Create .env file if it doesn't exis
            if [ ! -f .env ]; then
              echo "DATABASE_URL=postgresql+asyncpg://generous_user:generous_pass@db:5432/generoushands" > .env
            fi

            # Build and restart containers
            docker-compose build --no-cache
            docker-compose down

            # Run database migrations
            docker-compose up -d db
            sleep 10  # Wait for database to be ready
            docker-compose run --rm api alembic upgrade head

            # Start all services
            docker-compose up -d
